/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DownloadUrl { 'url' : string, 'quality' : string }
export interface Movie {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'thumbnailUrl' : string,
  'year' : bigint,
  'downloadUrls' : Array<DownloadUrl>,
  'language' : string,
  'synopsis' : string,
  'genre' : string,
  'addedAt' : bigint,
  'videoUrl' : string,
}
export interface _SERVICE {
  'addOrUpdateMovie' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      Array<DownloadUrl>,
      boolean,
    ],
    bigint
  >,
  'filterMovies' : ActorMethod<
    [[] | [string], [] | [bigint], [] | [string]],
    Array<Movie>
  >,
  'getAllMovies' : ActorMethod<[], Array<Movie>>,
  'getFeaturedMovies' : ActorMethod<[], Array<Movie>>,
  'getMovieById' : ActorMethod<[bigint], Movie>,
  'getMoviesByYear' : ActorMethod<[bigint], Array<Movie>>,
  'getRecentMovies' : ActorMethod<[bigint], Array<Movie>>,
  'initialize' : ActorMethod<[], undefined>,
  'removeMovie' : ActorMethod<[bigint], undefined>,
  'searchMovies' : ActorMethod<[string], Array<Movie>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];