/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DownloadUrl = IDL.Record({
  'url' : IDL.Text,
  'quality' : IDL.Text,
});
export const Movie = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'thumbnailUrl' : IDL.Text,
  'year' : IDL.Nat,
  'downloadUrls' : IDL.Vec(DownloadUrl),
  'language' : IDL.Text,
  'synopsis' : IDL.Text,
  'genre' : IDL.Text,
  'addedAt' : IDL.Int,
  'videoUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addOrUpdateMovie' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(DownloadUrl),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'filterMovies' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [IDL.Vec(Movie)],
      ['query'],
    ),
  'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getFeaturedMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getMovieById' : IDL.Func([IDL.Nat], [Movie], ['query']),
  'getMoviesByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Movie)], ['query']),
  'getRecentMovies' : IDL.Func([IDL.Nat], [IDL.Vec(Movie)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'removeMovie' : IDL.Func([IDL.Nat], [], []),
  'searchMovies' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DownloadUrl = IDL.Record({ 'url' : IDL.Text, 'quality' : IDL.Text });
  const Movie = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'thumbnailUrl' : IDL.Text,
    'year' : IDL.Nat,
    'downloadUrls' : IDL.Vec(DownloadUrl),
    'language' : IDL.Text,
    'synopsis' : IDL.Text,
    'genre' : IDL.Text,
    'addedAt' : IDL.Int,
    'videoUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addOrUpdateMovie' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(DownloadUrl),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'filterMovies' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [IDL.Vec(Movie)],
        ['query'],
      ),
    'getAllMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getFeaturedMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getMovieById' : IDL.Func([IDL.Nat], [Movie], ['query']),
    'getMoviesByYear' : IDL.Func([IDL.Nat], [IDL.Vec(Movie)], ['query']),
    'getRecentMovies' : IDL.Func([IDL.Nat], [IDL.Vec(Movie)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'removeMovie' : IDL.Func([IDL.Nat], [], []),
    'searchMovies' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };